In [16]:
import pandas as pd
import numpy as np
import os

In [17]:
# Specify the path to the predictions
FILE_LOCATION = "../../../data/evaluation/dataset_custom_8/specialized_qrf/predictions.csv"
NUMBER_OF_WEEK = 4
BOUNDS = ["inf", "pred", "sup"]

In [18]:
# Load predictions
predictions = pd.read_csv(FILE_LOCATION)

In [19]:
predictions

,station_code,week_0_pred,week_0_sup,week_0_inf,week_1_pred,week_1_sup,week_1_inf,week_2_pred,week_2_sup,week_2_inf,week_3_pred,week_3_sup,week_3_inf,ObsDate
0,6119020,14.418143,29.228571,76.695714,12.740714,26.242857,56.290000,12.009286,26.900000,71.448571,8.334143,18.900000,51.081429,2004-02-01
1,6119020,6.854143,12.085714,31.732857,5.150857,10.255714,29.620000,3.812714,11.518571,34.064286,4.731143,15.844286,39.484286,2004-04-25
2,6119020,8.200857,18.300000,50.017143,7.923857,19.700000,46.141429,5.335571,18.485714,52.047143,7.045143,26.400000,50.642857,2004-07-18
3,6119020,2.342429,3.970000,9.741286,1.967143,4.668571,26.114286,0.989143,3.924286,10.131286,1.112686,4.520000,26.066429,2004-10-10
4,6119020,8.494286,19.401429,38.511429,6.195571,21.535714,48.755714,5.335143,23.757143,58.508571,4.428571,16.814286,40.201429,2005-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1385,56992400,406.021336,534.418071,1198.873736,646.025966,1136.187443,1747.025260,359.971619,626.768629,1066.405524,381.432879,452.400586,593.046967,2014-04-20
1386,56992400,248.634420,301.496486,389.283043,134.079980,284.652729,354.082861,245.955903,281.194171,385.313317,231.335194,288.717743,448.272153,2014-07-13
1387,56992400,144.933521,182.894971,379.715364,133.726577,193.968857,437.009307,131.923869,237.994400,477.277813,107.904750,298.439457,814.849241,2014-10-05
1388,56992400,733.104793,1529.743700,2387.102711,744.542543,1327.454814,3190.844829,709.084577,1589.772357,4169.061146,598.232737,1414.632400,3115.814940,2014-12-28
1389,56992400,277.034690,326.750271,397.643269,202.148420,385.297100,731.194247,226.350573,355.073429,987.518956,223.863597,328.833771,630.225671,2015-03-22

### Check NaN values

In [20]:
print(f"Predictions contains {predictions.isna().sum().sum()} NaN values")

Predictions contains 0 NaN values

### Check Negative values

In [22]:
for i in range(1, NUMBER_OF_WEEK):
    for bound in BOUNDS:
        col_to_check = f"week_{i}_{bound}"
        negative_count = predictions[predictions[col_to_check] < 0].count().sum()
        print(f"Week {i} {bound} predictions contains {negative_count} negative values")

Week 1 inf predictions contains 0 negative values
Week 1 pred predictions contains 0 negative values
Week 1 sup predictions contains 0 negative values
Week 2 inf predictions contains 0 negative values
Week 2 pred predictions contains 0 negative values
Week 2 sup predictions contains 0 negative values
Week 3 inf predictions contains 0 negative values
Week 3 pred predictions contains 0 negative values
Week 3 sup predictions contains 0 negative values

### Check Negative values

In [29]:
predictions.shape

(1390, 14)

In [31]:
for i in range(1, NUMBER_OF_WEEK):
    col_prefix = f"week_{i}_"
    overlap_count = predictions[predictions[col_prefix + BOUNDS[0]] > predictions[col_prefix + BOUNDS[1]]]
    print(f"Week {i} {bound} predictions contains {overlap_count} overlap values")

Week 1 sup predictions contains       station_code  week_0_pred   week_0_sup   week_0_inf  week_1_pred  \
0          6119020    14.418143    29.228571    76.695714    12.740714
1          6119020     6.854143    12.085714    31.732857     5.150857
2          6119020     8.200857    18.300000    50.017143     7.923857
3          6119020     2.342429     3.970000     9.741286     1.967143
4          6119020     8.494286    19.401429    38.511429     6.195571
...            ...          ...          ...          ...          ...
1385      56992400   406.021336   534.418071  1198.873736   646.025966
1386      56992400   248.634420   301.496486   389.283043   134.079980
1387      56992400   144.933521   182.894971   379.715364   133.726577
1388      56992400   733.104793  1529.743700  2387.102711   744.542543
1389      56992400   277.034690   326.750271   397.643269   202.148420

       week_1_sup   week_1_inf  week_2_pred   week_2_sup   week_2_inf  \
0       26.242857    56.290000    12.009286    26.900000    71.448571
1       10.255714    29.620000     3.812714    11.518571    34.064286
2       19.700000    46.141429     5.335571    18.485714    52.047143
3        4.668571    26.114286     0.989143     3.924286    10.131286
4       21.535714    48.755714     5.335143    23.757143    58.508571
...           ...          ...          ...          ...          ...
1385  1136.187443  1747.025260   359.971619   626.768629  1066.405524
1386   284.652729   354.082861   245.955903   281.194171   385.313317
1387   193.968857   437.009307   131.923869   237.994400   477.277813
1388  1327.454814  3190.844829   709.084577  1589.772357  4169.061146
1389   385.297100   731.194247   226.350573   355.073429   987.518956

      week_3_pred   week_3_sup   week_3_inf     ObsDate
0        8.334143    18.900000    51.081429  2004-02-01
1        4.731143    15.844286    39.484286  2004-04-25
2        7.045143    26.400000    50.642857  2004-07-18
3        1.112686     4.520000    26.066429  2004-10-10
4        4.428571    16.814286    40.201429  2005-01-02
...           ...          ...          ...         ...
1385   381.432879   452.400586   593.046967  2014-04-20
1386   231.335194   288.717743   448.272153  2014-07-13
1387   107.904750   298.439457   814.849241  2014-10-05
1388   598.232737  1414.632400  3115.814940  2014-12-28
1389   223.863597   328.833771   630.225671  2015-03-22

[1390 rows x 14 columns] overlap values
Week 2 sup predictions contains       station_code  week_0_pred   week_0_sup   week_0_inf  week_1_pred  \
0          6119020    14.418143    29.228571    76.695714    12.740714
1          6119020     6.854143    12.085714    31.732857     5.150857
2          6119020     8.200857    18.300000    50.017143     7.923857
3          6119020     2.342429     3.970000     9.741286     1.967143
4          6119020     8.494286    19.401429    38.511429     6.195571
...            ...          ...          ...          ...          ...
1385      56992400   406.021336   534.418071  1198.873736   646.025966
1386      56992400   248.634420   301.496486   389.283043   134.079980
1387      56992400   144.933521   182.894971   379.715364   133.726577
1388      56992400   733.104793  1529.743700  2387.102711   744.542543
1389      56992400   277.034690   326.750271   397.643269   202.148420

       week_1_sup   week_1_inf  week_2_pred   week_2_sup   week_2_inf  \
0       26.242857    56.290000    12.009286    26.900000    71.448571
1       10.255714    29.620000     3.812714    11.518571    34.064286
2       19.700000    46.141429     5.335571    18.485714    52.047143
3        4.668571    26.114286     0.989143     3.924286    10.131286
4       21.535714    48.755714     5.335143    23.757143    58.508571
...           ...          ...          ...          ...          ...
1385  1136.187443  1747.025260   359.971619   626.768629  1066.405524
1386   284.652729   354.082861   245.955903   281.194171   385.313317
1387   193.968857   437.009307   131.923869   237.994400   477.277813
1388  1327.454814  3190.844829   709.084577  1589.772357  4169.061146
1389   385.297100   731.194247   226.350573   355.073429   987.518956

      week_3_pred   week_3_sup   week_3_inf     ObsDate
0        8.334143    18.900000    51.081429  2004-02-01
1        4.731143    15.844286    39.484286  2004-04-25
2        7.045143    26.400000    50.642857  2004-07-18
3        1.112686     4.520000    26.066429  2004-10-10
4        4.428571    16.814286    40.201429  2005-01-02
...           ...          ...          ...         ...
1385   381.432879   452.400586   593.046967  2014-04-20
1386   231.335194   288.717743   448.272153  2014-07-13
1387   107.904750   298.439457   814.849241  2014-10-05
1388   598.232737  1414.632400  3115.814940  2014-12-28
1389   223.863597   328.833771   630.225671  2015-03-22

[1390 rows x 14 columns] overlap values
Week 3 sup predictions contains       station_code  week_0_pred   week_0_sup   week_0_inf  week_1_pred  \
0          6119020    14.418143    29.228571    76.695714    12.740714
1          6119020     6.854143    12.085714    31.732857     5.150857
2          6119020     8.200857    18.300000    50.017143     7.923857
3          6119020     2.342429     3.970000     9.741286     1.967143
4          6119020     8.494286    19.401429    38.511429     6.195571
...            ...          ...          ...          ...          ...
1385      56992400   406.021336   534.418071  1198.873736   646.025966
1386      56992400   248.634420   301.496486   389.283043   134.079980
1387      56992400   144.933521   182.894971   379.715364   133.726577
1388      56992400   733.104793  1529.743700  2387.102711   744.542543
1389      56992400   277.034690   326.750271   397.643269   202.148420

       week_1_sup   week_1_inf  week_2_pred   week_2_sup   week_2_inf  \
0       26.242857    56.290000    12.009286    26.900000    71.448571
1       10.255714    29.620000     3.812714    11.518571    34.064286
2       19.700000    46.141429     5.335571    18.485714    52.047143
3        4.668571    26.114286     0.989143     3.924286    10.131286
4       21.535714    48.755714     5.335143    23.757143    58.508571
...           ...          ...          ...          ...          ...
1385  1136.187443  1747.025260   359.971619   626.768629  1066.405524
1386   284.652729   354.082861   245.955903   281.194171   385.313317
1387   193.968857   437.009307   131.923869   237.994400   477.277813
1388  1327.454814  3190.844829   709.084577  1589.772357  4169.061146
1389   385.297100   731.194247   226.350573   355.073429   987.518956

      week_3_pred   week_3_sup   week_3_inf     ObsDate
0        8.334143    18.900000    51.081429  2004-02-01
1        4.731143    15.844286    39.484286  2004-04-25
2        7.045143    26.400000    50.642857  2004-07-18
3        1.112686     4.520000    26.066429  2004-10-10
4        4.428571    16.814286    40.201429  2005-01-02
...           ...          ...          ...         ...
1385   381.432879   452.400586   593.046967  2014-04-20
1386   231.335194   288.717743   448.272153  2014-07-13
1387   107.904750   298.439457   814.849241  2014-10-05
1388   598.232737  1414.632400  3115.814940  2014-12-28
1389   223.863597   328.833771   630.225671  2015-03-22

[1390 rows x 14 columns] overlap values